using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TaxiWebApp.Models;

namespace TaxiWebApp.Controllers
{
    //Also describe way of handle error, either use try catch block on action method or override OnException 
    //Also handle in global file if in case missed something
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Us.";
            if (TempData.ContainsKey("ContactMessage"))
            {
                ViewBag.ContactMessage = TempData["ContactMessage"].ToString();
            }
            return View();
        }

        [HttpPost]
        public ActionResult Contact(ContactData model)
        {
            if (ModelState.IsValid)
            {
                //Send Email
                string Subject = "Travel Service Query";
                StringBuilder SB = new StringBuilder();
                SB.Append("<html> <body >");
                SB.Append("<table style='background-color:#f3f3f3;width:100%;border-collapse:collapse;border:1px solid #a5968c;font-size:15px;'>");
                SB.Append("<TR>");
                SB.Append("<TD>    !!! Do not reply as this Email is auto generated by follow-up system !!!	</TD>");
                SB.Append("</TR>");
                SB.Append("<tr>");
                SB.Append("<td style='color:White;background-color:orange;font-weight:700;font-size:16px;padding:2px;border-bottom:4px solid #eef3cf;'>");
                SB.Append(Subject);
                SB.Append("</td> </tr> <tr><td>");
                SB.Append("Thanks for contacting us,"+model.Name+".We will get back to you soon.");
                SB.Append("</td> </tr></body><br/><br/>");
                SB.Append("<tr><td><b>Thanks & Regards <br/>Travel Services Pvt. Ltd</b> </td></tr>");
                SB.Append("</html>");

                MailMessage mail = new MailMessage();
                mail.To.Add(model.Email);
              //  mail.From = new MailAddress("theamittomar@gmail.com");
                mail.CC.Add("amittomart4@gmail.com");
                mail.Subject = Subject;
                mail.Body = SB.ToString();
                mail.IsBodyHtml = true;
                mail.Priority = MailPriority.Normal;

                //value coming from web.config
                SmtpClient smtp = new SmtpClient();
                smtp.EnableSsl = true;
                smtp.Send(mail);

                //We want to keep data in another action as well
                TempData["ContactMessage"] = "We acknowledge your request,get back to you soon, Thanks.";

                return RedirectToAction("Contact");
            }
            return View(model);
        }

        #region Custom Error Message example

        // [HttpPost]
        //public ActionResult Contact(ContactData model)
        //{
        //    //try
        //    //{
        //    if (ModelState.IsValid)
        //    {
        //        //We want to keep data in another action as well
        //        TempData["ContactMessage"] = "We acknowledge your request,get back to you soon, Thanks.";
        //        return RedirectToAction("Contact");

        //        //*************Add Custom Error message example
        //        //if (model.Name == "Amit")
        //        //{
        //        //    ViewBag.ContactMessage = "We acknowledge your request,get back to you soon, Thanks.";
        //        //    return RedirectToAction("Contact");
        //        //}
        //        //else
        //        //{
        //        //    ModelState.AddModelError(string.Empty, "Name is not Amit");
        //        //    return View(model);
        //        //}
        //    }
        //    return View(model);
        //    //}
        //    //catch (Exception ex)
        //    //{
        //    //    ViewBag.ErrorObj = ex;
        //    //    return View("Error");
        //    //}
        //}

        #endregion

        //If we are not using try catch for block, or we forgot than override this function 
        //in controller and it will used for all action method  
        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;
            //Log the error!!
            //  _Logger.Error(filterContext.Exception);
            //Redirect or return a view, but not both.
            //  filterContext.Result = RedirectToAction("Index", "ErrorHandler");
            // OR 
            var model = new HandleErrorInfo(filterContext.Exception, "Controller", "Action");
            filterContext.Result = new ViewResult()
            {
                ViewName = "ErrorFromOnException",
                ViewData = new ViewDataDictionary(model)
            };
        }
    }
}